/**
 * Injects BACKEND_URL into production environment before `ng build`.
 * Set in Vercel: Settings → Environment Variables → BACKEND_URL
 * Example: https://ishqora-api.onrender.com (no trailing slash)
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = dirname(fileURLToPath(import.meta.url));
const projectRoot = join(root, '..');
const backend = (process.env.BACKEND_URL || '').trim().replace(/\/$/, '');
const envPath = join(projectRoot, 'src/environments/environment.production.ts');

const apiBaseUrl = backend;
const content = `/** Generated by scripts/prepare-vercel.mjs — do not edit apiBaseUrl by hand before deploy. */
export const environment = {
  production: true,
  apiBaseUrl: ${JSON.stringify(apiBaseUrl)}
};
`;

writeFileSync(envPath, content, 'utf8');

if (backend) {
  console.log(`[prepare-vercel] API → ${backend}`);
} else {
  console.warn('[prepare-vercel] BACKEND_URL missing — site will load but articles/API will fail.');
}
