/**
 * Injects BACKEND_URL into production environment before `ng build`.
 * Set in Vercel: Settings → Environment Variables → BACKEND_URL
 * Example: https://ishqora-api.onrender.com (no trailing slash)
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = dirname(fileURLToPath(import.meta.url));
const projectRoot = join(root, '..');
const backend = (process.env.BACKEND_URL || '').trim().replace(/\/$/, '');
const envPath = join(projectRoot, 'src/environments/environment.production.ts');

/** Same-origin: Vercel middleware proxies /api and /uploads to BACKEND_URL */
const apiBaseUrl = backend ? '' : '';
const content = `/** Generated by scripts/prepare-vercel.mjs */
export const environment = {
  production: true,
  apiBaseUrl: ''
};
`;

writeFileSync(envPath, content, 'utf8');

if (backend) {
  console.log(`[prepare-vercel] Proxy via middleware → ${backend}`);
} else {
  console.warn('[prepare-vercel] BACKEND_URL missing — set in Vercel env and redeploy.');
}
